### ISSUE TITLE
update vape independent (suggestion)

### ISSUE THREAD

**Issue by std-cin** [7GrandDadPGN/VapeV4ForRoblox#145]
I love vape independent and it kind of doesn't work anymore.
Here's what I noticed:

1. It's still using the old module creation structure (if you can call it like that): ``uilib["ObjectsThatCanBeSaved"]..`` instead of ``uilib.ObjectsThatCanBeSaved``
2. The discord is outdated. It's using the 7GrandDad#6656 which is probably not in use anymore.
now it's just some suggestions:
1. Let us use custom assets for tabs maybe?
2. Custom save file directory (e.g ``"customscript/savefile.txt"``)
3. Slider increments instead of being just 1.

**Comment by 7GrandDadPGN** [comment]
1. The documentation is indeed old
2. yeah I'll prob need to update the 
3. p sure you can if you download the assets yourself
4. would require some rewriting to the saving & loading code, maybe in the future
5. ![Code_dqvJIHWjT5](https://user-images.githubusercontent.com/29617380/233899898-871b18c6-6bfa-48a5-afe8-9e84e7050f85.png)
another property that's not mentioned since the docs are old, this should allow displaying decimal increments (then diving the value after by how much)

**Comment by 7GrandDadPGN** [comment]
Updated the documentation, please contact me about it "not working" in my testing it works fine.
